export enum ALLOWED_MOVEMENTS {
  ROCK = "rock",
  PAPER = "paper",
  SCISSORS = "scissors",
}

export enum ANIMATION_NAMES {
  HELLO = "Hello",
  PAPER = ALLOWED_MOVEMENTS.PAPER,
  ROCK = ALLOWED_MOVEMENTS.ROCK,
  SCISSORS = ALLOWED_MOVEMENTS.SCISSORS,
}